prometheus:
  server:
    service:
      type: ClusterIP

  serviceMonitors:
    enabled: true
    additionalServiceMonitors:
      - name: app-monitor
        selector:
          matchLabels:
            app: sample-app
        namespaceSelector:
          matchNames:
            - apps
        endpoints:
          - port: metrics
            path: /metrics
            interval: 30s

grafana:
  adminPassword: prom-operator
  service:
    type: ClusterIP
  persistence:
    enabled: false
  dashboards:
    default:
      sample-dashboard:
        gnetId: 1860
        revision: 23
        datasource: Prometheus