replicaCount: 1
image:
  repository: your-dockerhub-user/app
  tag: latest
  pullPolicy: IfNotPresent
service:
  name: sample-app
  type: ClusterIP
  port: 80
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi