name: Docker Build & Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sample-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run tests
        run: go test -v ./...

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.pedrohk }}
          password: ${{ secrets.dckr_pat_F2sljAbvnjhL_EnsOndgxuenpa0 }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./sample-app
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ secrets.pedrohk }}/app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max